version: '2'
services:

    nginx-proxy:
        image: jwilder/nginx-proxy
        ports:
        - "80:80"
#        - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
#            - /etc/apache2/ssl:/etc/nginx/certs

    web:
        build:
            context: ./
            dockerfile: docker/web.docker
        volumes:
            - ./:/var/www
        links:
            - app
        environment:
            - "VIRTUAL_HOST=laraveldocker.local"

    app:
        build:
            context: ./
            dockerfile: docker/app.docker
        volumes:
            - ./:/var/www
        links:
            - database
            - cache
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=cache"
    database:
        image: mysql:5.7
        environment:
            - "MYSQL_ROOT_PASSWORD=123"
            - "MYSQL_DATABASE=laraveldocker"
        ports:
            - "33061:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - database:db
        environment:
            - "PMA_USER=root"
            - "PMA_PASSWORD=123"
            - "PHP_UPLOAD_MAX_FILESIZE=100MB"
            - "VIRTUAL_HOST=pma.laraveldocker.local"

    cache:
        image: redis:3.0
        ports:
            - "63791:6379"
